### ISSUE TITLE
ISO 8859-1 encoded characters (esp umlauts) are corrupted

### ISSUE THREAD

**Issue by Throne3d** [Throne3d/node-irc#13]
Encountered in the `discord-irc` library, https://github.com/reactiflux/discord-irc/issues/237, but if IRC clients do heuristically detect the encoding, this library should also do it (presumably optionally) before passing the message to whatever hooks into it.

**Comment by Throne3d** [comment]
I don't particularly have a way to reproduce this at the moment so I can't go about fixing it. If anyone has information on how to reproduce (… preferably with some client I can freely install, or some message I can copy-paste) then that would be appreciated.

**Comment by Merri** [comment]
You can simply detect if the incoming message part is valid UTF-8 (for example: https://github.com/websockets/utf-8-validate). If it isn't, then it should be converted from an encoding to UTF-8. Easiest first step is to support only ISO-8859-1 to UTF-8. Full encoding detection is harder to implement and I don't know if there exists a JS lib for that.

**Comment by Throne3d** [comment]
Part of the reason I'd like a way to reproduce it, instead of just providing a fix, is that [this](https://github.com/Throne3d/node-irc/blob/master/lib/irc.js#L1223) seems like it should be doing something relating to this. Maybe the user who encountered the problem didn't have an `encoding` set? Maybe this library should default to UTF-8?

… I can probably come up with an example to reproduce this (by figuring out how to put some text in a specific encoding and copying it and seeing how the bot deals with it), but I've not worked with encodings before and I wanted to reproduce it in a live scenario instead of trying to create a breaking situation myself.

Thanks, though. I'll look into it, at some point.

**Comment by Merri** [comment]
You can reproduce it with almost any IRC client that has been around for a bit longer period of time, like set mIRC to use latin-1 :)

**Comment by Throne3d** [comment]
So it looks like (1) mIRC is really ugly, (2) Wine (as in 'Wine is not an emulator') works better than I thought, and (3) the library translates these characters just fine if you add `encoding: 'utf-8'` to the config (but not when you don't).

This requires that you install the dependencies `node-icu-charset-detector` and `iconv`, though, I think, else you get a bunch of ugly messages.

I'm gonna close this for now, unless anybody has more information to add.

**Comment by Throne3d** [comment]
See also #32, which adds a function (`irc.canConvertEncoding`, aliased also as `irc.Client.canConvertEncoding`) to check if the client is currently capable of converting between encodings.

**Comment by snohko** [comment]
**Hey*

My friend got a server that is ISO-89951.

How do I via screen + irssi do so whole irssi like the network im about to connect to using all ISO-89951.

i don't recall what to write in "_screen irssi <something something_>

Any ideas?

I have tried /set term_charset but still 'SSL HANDSHAKE".

I can connect to other SSL servers. But this one is all ISO-89951. Think it is because it ain't going to be easy to connect there.. I think 🤔 I recall something  like "screen irssi encoding ISO-89951 SOMETHING.. I don't remember that command with screen and screen -h don't mention it. 

Thanks!!
