### ISSUE TITLE
ghosting on connect

### ISSUE THREAD

**Issue by mekolat** [Throne3d/node-irc#45]
It should be possible to auto-ghost on connect when the nick differs from the desired nick and `irc.Client.autoRenick` is `true`;

If that's not possible it should at least be possible to pass an array of nicks to `irc.Client` so that the bot doesn't end up with names like `Guest3561` when they reconnect and their ghost is still present

**Comment by Throne3d** [comment]
When you say ghost, you mean using NickServ? That seems like it would need the bot to know it's logged in, so – only when it's successfully authenticated using SASL, or?

The bot shouldn't, at present, end up with nicknames like `Guest3561` anyway, unless the original nickname was `Guest356` and it had to go to `Guest3561` for a valid unused nickname (or it was `Guest` and it's tried that 3561 times)…? An array of nicks seems reasonable – I think I saw another fork which allowed you to pass a _function_, too.

**Comment by Throne3d** [comment]
I'm gonna close this for now, due to a lack of information.
