### ISSUE TITLE
Libiconv and ICU charset detector

### ISSUE THREAD

**Issue by JoinedSenses** [Throne3d/node-irc#52]
While these are optional dependencies for the discord-irc program, do you know of a method of installing libiconv and ICU on a windows machine? After hours of research, I'm still confused.

**Comment by Throne3d** [comment]
I'm honestly not sure how to do it. I just tried for a bit to get it to install, but encountered a few issues and couldn't get around them. There also doesn't seem to be an obvious set of steps.

It's sort of overkill, but if you're on Windows 10, you could look into installing the [Windows Subsystem for Linux](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux), then put node in there and use the instructions as for Ubuntu. Alternatively you could try asking over at https://github.com/mooz/node-icu-charset-detector/issues?

**Comment by JoinedSenses** [comment]
There are already issues on the same subject there, although none of them were conclusive or helpful for windows. 

I'm unsure of any other methods of contact with you at the moment, I just wanted to give you an update on discord-irc and everything seems to be going well so far. 
Typically, the program would disconnect once a day, so I ended up having to write a batch file to restart it. I've had it running for over 24 hours with no issue yet.

**Comment by Throne3d** [comment]
Hrm. It's awkward that there's no clear solution – I'm not sure how to help further, in that case, though Windows Subsystem for Linux definitely works.

I'm glad discord-irc is once again working! I have no idea when the upstream library broke (snekfetch, I believe? I'm assuming that's the relevant issue, at least) – but it's good it's fixed. As for contact methods, the recommended way would probably be the gitter for this repository – <https://gitter.im/node-irc>. Other than that, I'm sometimes on IRC in freenode, with the obvious username, or Discord. I'm used to sites having a PM system, which I think GitHub doesn't.

**Comment by Throne3d** [comment]
Forgot to say – I'm gonna close this issue for now, since it seems like a thing I can't readily fix (and it looks like it's known about upstream).
