### ISSUE TITLE
irc-upd and vscode

### ISSUE THREAD

**Issue by albertosantini** [Throne3d/node-irc#69]
A few info to use `irc-upd` with the code editor `Visual Studio Code`.

Configuring the files below, you don't get ts lint errors when you use the package `irc-upd` (not while you develop the package).

Just my two cents.

`jsconfig.json`
```
{
    "compilerOptions": {
        "checkJs": true,
        "target": "es2017",
        "moduleResolution": "node"
    }
}
```

`global.d.ts`
```
import { Client } from "irc-upd";
import { EventEmitter } from "events";

declare module "irc-upd" {
    export interface Client extends EventEmitter {
    }
}

```

**Comment by Throne3d** [comment]
I forgot to respond to this – I've never looked into TypeScript, but it looks like this is an issue with it knowing that Client is meant to inherit EventEmitter. This might be more generally solved by looking into TypeScript bindings for the library? (I haven't touched it much, just know the vague overview.)

**Comment by albertosantini** [comment]
Correct. 

It should be a matter of types definitions.
Me too I play with types only in cases like this.

Indeed I closed the issue.
Just a reminder for another user or for contributing later. :)
