### ISSUE TITLE
ChannelRestrict? invite or a sajoin the bot join

### ISSUE THREAD

**Issue by MalaGaM** [Throne3d/node-irc#90]
When any user uses /invites on the robot, the robot joins the room automatically. Even if the living room did not configure in the robot.

In some cases, this attitude was not wanted.
How can you prevent unconfigured rooms from being joined?
Maybe a boolean ChannelRestrict option in irc.Client (server, nick [, options])?

Something that at the 'join' event checks, if this is a channel allowed by configuration if the ChannelRestrict option is set to true?

*Same thing when an IRC operator uses a SAJOIN

**Comment by Throne3d** [comment]
Hi there! I just tested: this library does not automatically join a channel when `/invite`d to a channel (and I'm not sure about an SAJOIN).

Small example, using irc-upd 0.11.0:

```js
const irc = require('irc-upd');

const ircClient = new irc.Client(
  someServer, // replace with "irc.some-server.com"
  "testbot",
  {
    channels: ["#testbed"],
    autoRenick: true,
    encoding: "utf-8",
  },
);

ircClient.on('registered', () => console.log("Connected to IRC"));
ircClient.on('message', (author, channel, text) => console.log(`${channel} <${author}> ${text}`));
ircClient.on('invite', (channel, from) => console.log(`INVITE from ${from} to ${channel}`));
```

And then, after the bot joins the server, I use `/invite testbot`, and the bot logs the invite, but does not join the server.

Did you mean to file this against reactiflux/discord-irc? That bot _does_ have an auto-joining functionality, but it should be restricting it based on the channels you set in configs: https://github.com/reactiflux/discord-irc/blob/56d1c841474e5588e9d0b78f113562372fc6a307/lib/bot.js#L250

If not, can you provide a repro script maybe?

**Comment by Throne3d** [comment]
I'll close this issue for now, but if you can come up with a repro, I could try to help fix this issue then!
